# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bT1jbUNmsbtN-RbhDPdvy310DTlL3jgN
"""

pip install transformers datasets torchaudio librosa ffmpeg

!pip install transformers datasets torchaudio librosa ffmpeg

from google.colab import drive
drive.mount('/content/drive')

from transformers import pipeline
import torch
import os

audio_path = '/content/drive/MyDrive/audio.mp3'

device = "cuda:0" if torch.cuda.is_available() else "cpu"
pipe = pipeline(
    model="openai/whisper-base",
    task="automatic-speech-recognition",
    device=0 if device == "cuda:0" else -1
)

print("Transcribing...")
result = pipe(audio_path)

print("\n--- Transcription ---\n")
print(result['text'])

output_path = '/content/drive/MyDrive/transcription.txt'
with open(output_path, "w") as f:
    f.write(result['text'])